(deftheme spaceduck-void
  "Created 2021-07-23.")

(custom-theme-set-faces
 'spaceduck-void
 '(default ((t (:family "Iosevka" :foundry "CYEL" :width normal :height 143 :weight normal :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#ecf0c1" :background "#0f111b" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#ecf0c1"))))
 '(fixed-pitch ((t (:family "Iosevka" :foundry "CYEL" :height 143))))
 '(variable-pitch ((t (:family "DejaVu Sans" :foundry "PfEd" :height 159))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#50567f"))))
 '(highlight ((t (:background "#252942"))))
 '(region ((t (:extend t :background "#30365F"))))
 '(shadow ((t (:foreground "dim gray"))))
 '(secondary-selection ((t (:extend t :background "#5ccc96"))))
 '(trailing-whitespace ((t (:foreground "#000000" :background "#e33400"))))
 '(font-lock-builtin-face ((t (:foreground "#5ccc96"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#30365F"))))
 '(font-lock-comment-face ((t (:slant italic :foreground "dim gray"))))
 '(font-lock-constant-face ((t (:foreground "#ce6f8f"))))
 '(font-lock-doc-face ((t (:foreground "#00a3cc"))))
 '(font-lock-function-name-face ((t (:foreground "#f2ce00"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "#5ccc96"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#f2ce00"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#00a3cc"))))
 '(font-lock-type-face ((t (:foreground "#7a5ccc"))))
 '(font-lock-variable-name-face ((t (:foreground "#ecf0c1"))))
 '(font-lock-warning-face ((t (:foreground "#e33400"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:foreground "#7a5ccc" :underline t))))
 '(link-visited ((t (:foreground "#114fd6" :underline t))))
 '(fringe ((t (:foreground "#5ccc96" :background "#0f111b"))))
 '(header-line ((t (:box nil :foreground "grey90" :background "grey20" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "#7a5ccc" :background "#114fd6"))))
 '(mode-line ((t (:foreground "#ecf0c1" :background "#30365F"))))
 '(mode-line-buffer-id ((t (:background "#30365F" :foreground "#7a5ccc"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t nil)))
 '(mode-line-inactive ((t (:foreground "#30365F" :background "#0f111b"))))
 '(isearch ((t (:foreground "#000000" :background "#ecf0c1"))))
 '(isearch-fail ((t (:foreground "#000000" :background "#e33400"))))
 '(lazy-highlight ((((class color) (min-colors 88) (background light)) (:background "paleturquoise")) (((class color) (min-colors 88) (background dark)) (:background "paleturquoise4")) (((class color) (min-colors 16)) (:background "turquoise3")) (((class color) (min-colors 8)) (:background "turquoise3")) (t (:underline (:color foreground-color :style line)))))
 '(match ((t (:background "#f2ce00"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'spaceduck-void)
